version: '3'

services:
  data-db:
    image: machbase/machbase
    volumes:
      - data_machbase:/home/machbase/machbase/dbs
    ports:
      - "5656:5656"

  web-db:
    image: postgres:11
    environment:
      - POSTGRES_DB=uyeg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=suin1098
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"
    volumes:
      - data_postgres:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    links:
      - web-db
    depends_on:
      - web-db
    working_dir: /
    command: flask run -h 0.0.0.0
    volumes:
      - ./app/:/app/

volumes:
  data_postgres: {}
  data_machbase: {}