version: '3.3'

services:
  data-db:
    image: machbase/machbase
    volumes:
      - machdata:/home/machbase/machbase/dbs
    stdin_open: true
    tty: true
    expose:
      - "5001"
      - "5656"

  web-db:
    image: postgres:11
    environment:
      - POSTGRES_DB=uyeg
      - POSTGRES_USER=its
      - POSTGRES_PASSWORD=1234QWER
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    links:
      - data-db
      - web-db
    depends_on:
      - data-db
      - web-db
    working_dir: /
    command: flask run -h 0.0.0.0
    volumes:
      - ./app/:/app/

volumes:
  pgdata: {}
  machdata: {}
