version: '3'

services:
  web-db:
    image: postgres
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - FLASK_APP=app
    ports:
      - "5000:5000"
    working_dir: /
    command: flask run -h 0.0.0.0
    volumes:
      - ./app/:/app/